# Do Not change ----------------
name      : M1
uuid      : 
type      : microscope
# ------------------------------

hardware:
  pico         : [pico1, null]
  camera       : rpi-hq
  illumination : CA_PWM_RGB_LED_5mm

